### ISSUE TITLE
Installs "test" into Python path

### ISSUE THREAD

**Issue by yigitsever** [sckott/habanero#109]
Seems like #105 is recurring again

Discovered the bug due to `i3-layouts` having the same issue: https://github.com/eliep/i3-layouts/issues/24

```
python-habanero: /usr/lib/python3.10/site-packages/test/__init__.py exists in filesystem (owned by i3-layouts)
python-habanero: /usr/lib/python3.10/site-packages/test/__pycache__/__init__.cpython-310.opt-1.pyc exists in filesystem (owned by i3-layouts)
python-habanero: /usr/lib/python3.10/site-packages/test/__pycache__/__init__.cpython-310.pyc exists in filesystem (owned by i3-layouts)
```

**Comment by yigitsever** [comment]
Oops, I've been getting a (very) outdated version, I should've checked that before creating an issue, sorry!

(https://aur.archlinux.org/packages/python-habanero)

**Comment by sckott** [comment]
glad it's sorted out!
