### ISSUE TITLE
Month returned by habanero.cn.content_negotiation(ids = doi) no longer in curly brackets

### ISSUE THREAD

**Issue by tardigradus** [sckott/habanero#144]
With Python 3.6.8 and habanero 0.7.4, I have been successfully downloading BibTeX files and parsing them with [BibtexParser](https://bibtexparser.readthedocs.io/en/main/index.html) for the last couple of years.  However, some time between the middle of September 2023 and now, the format of the BibTex file I get via ```habanero.cn.content_negotiation(ids = doi)``` changed:  The value of the field ```month``` is no longer enclosed in curly brackets.

So whereas in the middle of September 2023 I got:
```
@article{Zupan2023,
 author = {Hana Zupan and Frederick Heinz and Bettina G. Keller},
 doi = {10.1139/cjc-2022-0282},
 journal = {Canadian Journal of Chemistry},
 month = {sep},
 number = {9},
 pages = {710--724},
 publisher = {Canadian Science Publishing},
 title = {Grid-based state space exploration for molecular binding},
 url = {https://doi.org/10.1139/cjc-2022-0282},
 volume = {101},
 year = {2023}
}
```
I now get
```
@article{Zupan2023,
 author = {Hana Zupan and Frederick Heinz and Bettina G. Keller},
 doi = {10.1139/cjc-2022-0282},
 journal = {Canadian Journal of Chemistry},
 month = sep,
 number = {9},
 pages = {710--724},
 publisher = {Canadian Science Publishing},
 title = {Grid-based state space exploration for molecular binding},
 url = {https://doi.org/10.1139/cjc-2022-0282},
 volume = {101},
 year = {2023}
}
```
This is then causing ```BibtexParser``` to fail.

I assume this is not directly a problem with ```habanero```, but this a known issue?

Edit: ```doi2bib``` has the same issue: https://www.doi2bib.org/bib/10.1139/cjc-2022-0282

**Comment by sckott** [comment]
Thanks and sorry about the delay! Life events made it hard to do any paid or non-paid work. Having a look

**Comment by sckott** [comment]
I can replicate the issue myself. 

It does seem like a bare string like `sep` shouldn't be allowed given the text in https://www.bibtex.org/Format/ 

However, I'm not sure it's within scope to fix these issues in this package. I"ll check if it can be done easily

**Comment by sckott** [comment]
watch https://github.com/sciunto-org/python-bibtexparser/issues?q=is%3Aissue+is%3Aopen+label%3Av2

**Comment by sckott** [comment]
@tardigradus Okay, you can try the fixed version on main branch here - install from github, not on pypi yet.

**Comment by tardigradus** [comment]
Sorry for not getting round to this earlier.

I assumed that version `1.2.6` contains the fixes you made, so I installed that with `pip`.  I also had to `bibtexparser` to version 2, but I now get the month in curlies, as desired.  Thanks for fixing.

**Comment by sckott** [comment]
thanks @tardigradus yeah there's an optional install for bibtex - see https://github.com/sckott/habanero?tab=readme-ov-file#installation

**Comment by hseg** [comment]
Hi, can you please make the running of
`test-content_negotiation::test_content_negotiation_bad_bibtex` conditional on
if `bibtexparser` is installed? Given that you've made it an optional
dependency, it makes it harder to test an installation of `habanero` will work
with a bare `python -m pytest`.

At the moment, I need to tell the users of the AUR package to either install
`python-bibtexparser` for the tests, or to manually disable the tests, which
isn't a great situation.

**Comment by hseg** [comment]
It seems it'd be enough to mark that test as
`@pytest.importorskip("bibtexparser")`, see
https://docs.pytest.org/en/stable/reference.html#pytest-importorskip

**Comment by sckott** [comment]
> can you please make the running of
test-content_negotiation::test_content_negotiation_bad_bibtex conditional on
if bibtexparser is installed?

Good idea, sorry I missed that, looking at the PR now ...
