### ISSUE TITLE
Possibly use module package architecture instead of classes

### ISSUE THREAD

**Issue by sckott** [sckott/habanero#19]
might be simpler, like did for `pygbif`

**Comment by afandian** [comment]
This would be suitable for static helper functions (like date transform) but I think classes is best, especially when you might start to get state involved (e.g. deep paging or query builders).

Suggest probably a combination of both: module functions for despatching queries, but class hierarchies for results, and operations that can happen on results. Getting state mixed up with modules is a bad idea.

**Comment by sckott** [comment]
@afandian  Thanks for the feedback. Yeah, esp. maintaining state alone is a good reason for using classes.
