### ISSUE TITLE
DOIs for works

### ISSUE THREAD

**Issue by mbrunnen** [sckott/habanero#40]
I want to get meta data from a known DOI. The URL is:
[http://api.crossref.org/works/10.1109/MWC.2007.358967](http://api.crossref.org/works/10.1109/MWC.2007.358967)

My code is:
```
from habanero import Crossref

cr = Crossref()
cr.works(ids="10.1109/MWC.2007.358967")
```
But  habanero is requesting the very unspecific url:
[http://api.crossref.org/works/](http://api.crossref.org/works/)
I looked it up in the file `request_class.py` in the class function `Request._url()`.
I'm just starting with habanero, so perhaps it's just me ...

**Comment by sckott** [comment]
Good catch, tests should have caught that, will fix that. 

Weird, I must have slipped up at some point when I was adding support for cursor for deep paging. fixing

**Comment by sckott** [comment]
closing, if not fixed, reopen

**Comment by mbrunnen** [comment]
Now it works :+1:
