### ISSUE TITLE
Search for punctuation in title?

### ISSUE THREAD

**Issue by brandonStell** [sckott/habanero#64]
Is there a way to return results using query_title that have "[Retracted]" in the title but not "retracted"?

**Comment by sckott** [comment]
i see you asked https://github.com/CrossRef/rest-api-doc/issues/283 - that's the better place to ask, we can add an example in docs here

**Comment by brandonStell** [comment]
OK.  Thought maybe I had missed something.

**Comment by sckott** [comment]
since this is a task to do after getting data back, closing this
