### ISSUE TITLE
Changelog.rst missing from pypi distribution

### ISSUE THREAD

**Issue by oaken-source** [sckott/habanero#71]
Downloading the following source releaese from the pypi page (https://pypi.python.org/pypi/habanero#downloads)

https://pypi.python.org/packages/6a/48/3396b520da48fa7d645d29ce1de6ca706fa9f4ce37a3ea5019e1f7662cac/habanero-0.6.0.tar.gz#md5=3646ed46c855c0c3a3d43e2293061d93

and then invoking `python setup.py install`

produces the following error:

```
 Traceback (most recent call last):
   File "setup.py", line 17, in <module>
     with codecs.open('Changelog.rst', 'r', 'utf-8') as f:
   File "/usr/lib/python3.6/codecs.py", line 897, in open
     file = builtins.open(filename, mode, buffering)
 FileNotFoundError: [Errno 2] No such file or directory: 'Changelog.rst'
```

The Changelog.rst file is missing from the distributed source tarball.

**Comment by sckott** [comment]
thanks @oaken-source 

i'll have a look , not sure why that's happening.

**Comment by sckott** [comment]
okay, added a manifest file to include chanloge, docs, and test files, next push up to pypi should fix this
