### ISSUE TITLE
get citing works for a given DOI

### ISSUE THREAD

**Issue by tschoonj** [sckott/habanero#74]
Hi,

I was wondering if it is possible to get the DOIs of works that cite a given DOI.
I only managed to find how many times a given DOI is cited, but I would like to get the DOIs as well...

Thanks in advance,

Tom

**Comment by sckott** [comment]
thanks for your question @tschoonj 

it's not possible via the Crossref API. that is locked down data for publishers. 

one option is to go through Pubmed - i don't know the Python clients for entrez api but I'm sure there are many. 

Another is the http://opencitations.net/ project, i know they have a sparql endpoint

**Comment by tschoonj** [comment]
Thanks for the reply Scott!
