### ISSUE TITLE
Update PyPI upload

### ISSUE THREAD

**Issue by rgieseke** [sckott/habanero#75]
Thanks for this awesome tool!

Could you update the PyPI download with '0.6.0.3' ?

I just struggled a bit with the UTF-8 encoding issue ...

My workaround is to install with `pip install https://github.com/sckott/habanero/archive/master.zip`

[Edited: Fixed version number]

**Comment by sckott** [comment]
thanks for the issue and thanks for trying it. 

good idea, there's two other issues fixed as well, will push soon

**Comment by rgieseke** [comment]
Run into this again ... would be much appreciated :-)

**Comment by sckott** [comment]
Sorry about delay, will get it up today

**Comment by sckott** [comment]
its up now on pypi, let me know if any problems

**Comment by rgieseke** [comment]
Awesome, works perfectly now! Thanks al lot!
