### ISSUE TITLE
Feature request: progress indicator when deep paging

### ISSUE THREAD

**Issue by gorbynet** [sckott/habanero#77]
When systematically retrieving large data sets, it would be useful to have some way of measuring progress through the data harvest, e.g. show how many records have been retrieved, and how many there are in total, while the retrieval is ongoing.

**Comment by sckott** [comment]
thanks @gorbynet 

I assume you mean with deep paging? looking into it, not done progress bars before in python

**Comment by sckott** [comment]
maybe https://github.com/weecology/retriever/blob/0112008b710d176fc543be174bcd1205cb1fef1e/retriever/lib/engine.py#L455 using https://pypi.org/project/tqdm/

**Comment by sckott** [comment]
clint is another option

**Comment by sckott** [comment]
thanks, i'll experiment and ask for your feedback

**Comment by sckott** [comment]
this is more complicated than i thought. we need i think to have an idea of how many requests we'll make for a progress bar to work.

we're doing requests in a while loop https://github.com/sckott/habanero/blob/master/habanero/request_class.py#L68-L73 - we need to look at total results found by the server and also cursor_max

**Comment by sckott** [comment]
okay, install from `progress-bar` 

```
pip3 install --user https://github.com/sckott/habanero/archive/progress-bar.zip
```

and try e.g., 

```python
from habanero import Crossref
cr = Crossref()
res = cr.works(query = "octopus", cursor = "*", limit = 500, progress_bar = True)
```

**Comment by sckott** [comment]
let me know what you think 

the progress bar is not integrated into requests - it's only activeated when deep paging - it's just a progress bar on the while loop that uses an estimate of how many requests will be done

**Comment by sckott** [comment]
any thoughts on this @gorbynet ?

**Comment by gorbynet** [comment]
Apologies - this my personal Github account, and I only use the Crossref library for work, and haven't looked at it for months. I've got an audit that needs the deep paging, so I'll have a look at this now.

**Comment by gorbynet** [comment]
Hi @sckott , that works perfectly. Thank you!

**Comment by sckott** [comment]
great, glad it works. I'll merge this into master soon
