### ISSUE TITLE
Wiki: download PDF based on DOI

### ISSUE THREAD

**Issue by Metasoliton** [sckott/habanero#79]
Hi there, great work!!!

I am a first-time user, trying to wrap my head around dowloading a PDF based on its DOI, something like 
doi.download('10.1590/0102-311x00133115', '~/Downloads/')
that would result in the PDF landing in my Downloads folder.

I guess this is something very simple, however I could not find any example. Would you please provide one, perhaps even as a Wiki entry? 

Many thanks & Merry Christmas,
Stav

**Comment by sckott** [comment]
thanks for your question. 

`habanero` doesn't include any full text download or extraction itself. 

i started `pyminer` https://github.com/sckott/pyminer for that purpose - it needs a bit of work though, currently on vacation, will ping you when I get it working

**Comment by sckott** [comment]
@Metasoliton okay, i've worked on `pyminer` a bit https://github.com/sckott/pyminer#installation - it's got some rough edges still, but I think it's mostly working

**Comment by sckott** [comment]
if you have any `pyminer` questions/issues please open those over there
