### ISSUE TITLE
How to use polite pool in content_negotiation?

### ISSUE THREAD

**Issue by Xunius** [sckott/habanero#81]
Hi,

I'm currently developing a reference manager tool and I'm learning how to use Crossref. For now I only need to use the `content_negotiation()` function to get an bibtex entry from DOI. I saw the "The Polite Pool" section in the doc of `Crossref`, but no relevant info in `content_negotiation()`. How should I ensure polite pool practices using `content_negotiation()`?

Thanks

**Comment by sckott** [comment]
thanks for the issue  @Xunius 

"Polite pool" only exists for the Crossref API at https://github.com/CrossRef/rest-api-doc - which is what most of the methods in the `habanero.Crossref` module work with. For content negotation, requests of all formats (except one) go to a different place, documented at https://crosscite.org/docs.html . The only format that goes to the Crossref API, and where the polite pool applies, is the citeproc-json format. 

side note that we actually send the `mailto` header with the user email with all content negotation requests, but it should only have an effect when `format = "citeproc-json"`

**Comment by Xunius** [comment]
@sckott Many thanks for the info!
