### ISSUE TITLE
CrossRef API has deprecated `query.title` in favour of `query.biliographic`

### ISSUE THREAD

**Issue by jvansan** [sckott/habanero#85]
It seems that the CrossRef API has removed the `query.title` URL as I am now getting a 400 error code.
```
{"status":"failed","message-type":"validation-failure","message":[{"type":"unknown-parameter","value":"query.title","message":"Parameter query.title has been deprecated. Please use query.bibliographic instead. See https://status.crossref.org/incidents/4y45gj63jsp4 "}]}
```

The URL listed in the [returned JSON](https://status.crossref.org/incidents/4y45gj63jsp4) says that the query.title endpoint has been blocked now. It seems that all instances of `query.title` can be replaced with `query.bibliographic` but this should be verified.

This is also reflected in their docs: 
https://github.com/CrossRef/rest-api-doc/commit/d28ff01b2b2f380ebd9dd14e8b4eaf589ccd6711

Although I tried to double check, I'm sorry if this is a duplicate.

**Comment by sckott** [comment]
thanks @jvansan for this! 

i can replicate the issue, fixing now

**Comment by sckott** [comment]
reinstall from here and let me know if it works `sudo pip install git+git://github.com/sckott/habanero.git#egg=habanero`
