### ISSUE TITLE
Get request url

### ISSUE THREAD

**Issue by gneotel** [sckott/habanero#86]
Hi,
after a request like:
    cr = Crossref()
    Crossref(mailto = "dude@gmail.com")
    x = cr.works(query_author = "DUDE", filter=my_filter)
is there a way to get from the Crossref object the complete request url with query and filters?
Ideally pasting it on a browser I should get the json results.

It would be really helpful for filters tuning.

Thanks a lot.

**Comment by sckott** [comment]
Thanks for your question, you can turn on verbose curl output - see "Verbose curl output" section in the docs https://habanero.readthedocs.io/en/latest/modules/crossref.html#

**Comment by gneotel** [comment]
Thank you!
