### ISSUE TITLE
Support for DOI Creation

### ISSUE THREAD

**Issue by WolfgangFahl** [sckott/habanero#87]
Is support for https://support.datacite.org/docs/api-create-dois planned?

**Comment by sckott** [comment]
thanks for your question @WolfgangFahl 

habanero is a client for Crossref, not Datacite. Did you mean to open this issue in a repository for the Datacite API?

**Comment by WolfgangFahl** [comment]
Indeed https://pypi.org/project/datacite/ might be the project this issue needs to be addressed to
