### ISSUE TITLE
`limit` option doesn't work for the cr.members route

### ISSUE THREAD

**Issue by Bubblbu** [sckott/habanero#91]
I'm on python 3.6.10 and using the latest habanero version (0.7.4)

the `limit` option doesn't seem to be working.

`cr.members(ids=2984, works=True, facet="issn:*", limit=0)` returns the default 20 items.

wondering if this has to do with the mismatch between keywords `limit` & `rows`?

**Comment by sckott** [comment]
thanks for the report - having a look

**Comment by sckott** [comment]
@Bubblbu reinstall from here and try again
