### ISSUE TITLE
New Crossref REST API coming soon

### ISSUE THREAD

**Issue by ppolischuk** [sckott/habanero#96]
Hi, 

Thank you for maintaining one of the documented libraries for using the Crossref REST API.

We’ve been working on a new version of the REST API, replacing the Solr backend with Elasticsearch and moving from our own hardware in a datacenter to a cloud platform.

We plan to cutover to the new version shortly (expect an official announcement on our blog in the next few days with more details), and wanted to invite you to test it out before the official cutover.

Please check it out at [https://api.production.crossref.org/](https://api.production.crossref.org/)

During the cutover phase (expected to last a few weeks), traffic will be redirected to the above domain on a pool by pool basis. Once all traffic is using the new service, we will continue to use the `api.crossref.org` domain, so please do not update anything to use the temporary domain.

Let me know if you have any questions. Issues can be filed into our [GitLab issue repository](https://gitlab.com/crossref/issues/issues/), or I’ll keep an eye on this thread.

Thanks again,
Patrick

**Comment by sckott** [comment]
Thanks @ppolischuk for the heads up. 

Is there a summary somewhere of the changes in the new API vs. the old one?

**Comment by ppolischuk** [comment]
I have a post scheduled to go live on the Crossref blog on Tuesday that includes more details about changes and what to expect during the cutover. If you would like it before then I could share a draft with you. Please email me at ppolischuk@crossref.org if so.

**Comment by sckott** [comment]
note to self: blog post with details https://www.crossref.org/blog/behind-the-scenes-improvements-to-the-rest-api/
